[enhancement] Move logger calls in subroutine #57
Closes #57

diff --git a/openwrt-openwisp-monitoring/files/monitoring.init b/openwrt-openwisp-monitoring/files/monitoring.init
--- a/openwrt-openwisp-monitoring/files/monitoring.init
+++ b/openwrt-openwisp-monitoring/files/monitoring.init
@@ -39,20 +39,6 @@ start_service() {
 	[ -n "$key" ] && key="--key $key"
 	[ -n "$verify_ssl" ] && verify_ssl="--verify_ssl $verify_ssl"
 
-	if [ -z "$base_url" ]; then
-		logger -s "url is not set, please add it to /etc/config/openwisp" \
-			-t openwisp-monitoring \
-			-p daemon.err
-		exit 1
-	fi
-
-	if [ -z "$uuid" ] || [ -z "$key" ]; then
-		logger -s "uuid or key are not set, please add these to /etc/config/openwisp" \
-			-t openwisp-monitoring \
-			-p daemon.err
-		exit 1
-	fi
-
 	# for openwisp-monitoring
 	config_load openwisp-monitoring
 	config_get monitored_interfaces monitoring monitored_interfaces "*"
@@ -62,12 +48,8 @@ start_service() {
 	config_get max_retries monitoring max_retries "5"
 
 	interval="$(time_to_seconds "$interval")"
-	if [ "$interval" -lt 1 ]; then
-		logger -s "Interval is invalid. Use time value(eg: '10', '2m', '3h', '1d')" \
-			-t openwisp-monitoring \
-			-p daemon.err
-		exit 1
-	fi
+	[ -z "$interval" ] && { echo "Interval is invalid. Use time value(eg: '10', '2m', '3h', '1d')" 1>&2 && exit 1; }
+
 	interval="--interval $interval"
 	verbose="--verbose_mode ${verbose_mode:-0}"
 	set -- --monitored_interfaces \""$monitored_interfaces"\"
@@ -79,25 +61,19 @@ start_service() {
 	# shellcheck disable=SC2086
 	procd_set_param command $PROG $interval $monitored_interfaces $verbose $required_memory --mode collect
 	procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
-	[ "$verbose_mode" -eq "1" ] && procd_set_param stdout 1 && procd_set_param stderr 1
 	procd_close_instance
 
 	procd_open_instance "openwisp-monitoring_send_data"
 	# shellcheck disable=SC2086
 	procd_set_param command $PROG $base_url $uuid $key $verify_ssl $interval $verbose $max_retries --mode send
 	procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
-	[ "$verbose_mode" -eq "1" ] && procd_set_param stdout 1 && procd_set_param stderr 1
 	procd_close_instance
 
-	logger -s "$PROG_NAME started" \
-		-t openwisp-monitoring \
-		-p daemon.info
+	logger -s "$PROG_NAME started" -t openwisp-monitoring -p daemon.info
 }
 
 stop_service() {
-	logger -s "$PROG_NAME stopping" \
-		-t openwisp-monitoring \
-		-p daemon.info
+	logger -s "$PROG_NAME stopping" -t openwisp-monitoring -p daemon.info
 }
 
 service_triggers() {
